# Generated by Django 4.0.6 on 2022-07-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAtelier', models.CharField(max_length=240)),
                ('participant', models.CharField(max_length=240)),
                ('createdDateAtelier', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=240)),
                ('prenomClient', models.CharField(max_length=240)),
                ('emailClient', models.EmailField(max_length=254)),
                ('mobileClient', models.CharField(max_length=20)),
                ('inscriptionClient', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomConsultant', models.CharField(max_length=240)),
                ('prenomConsultant', models.CharField(max_length=240)),
                ('emailConsultant', models.EmailField(max_length=254)),
                ('mobileConsultant', models.CharField(max_length=20)),
                ('insciptionConsultant', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
