# Generated by Django 4.0.6 on 2022-07-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='majDateAtelier',
            field=models.DateField(auto_now=True),
        ),
    ]
