# Generated by Django 4.0.6 on 2022-07-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0002_atelier_majdateatelier'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
